name: Build and Deploy Debian Package APT Repo

on:
  push:
    branches:
      - main
      - github-actions-*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Prepare Build Environment
        run: |
          set -euo pipefail
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y pipx
          pipx ensurepath
          pipx uninstall ansible-core
          "$GITHUB_WORKSPACE/tools/ansible/install-ansible.sh"

      - name: Build Debian Packages
        run: |
          set -euo pipefail
          export WORKSPACE="$GITHUB_WORKSPACE"
          cd "$WORKSPACE/build" && ./run-build-packages-one-target.sh --target ubuntu2404 --force-build

      - name: Upload .deb Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: deb-packages
          path: ./packages/ubuntu2404/*.deb
          retention-days: 4
          if-no-files-found: error

  deploy:
    needs:
      - build
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pages: write
      id-token: write
      actions: read
    concurrency:
      group: "pages"
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install APT Repository Tools
        run: |
          set -euo pipefail
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y --no-install-recommends apt-utils gnupg gzip

      - name: Download .deb Artifacts from Build Workflow
        uses: actions/download-artifact@v8
        with:
          name: deb-packages
          path: ./build-output

      - name: Generate APT Repository
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          APT_REPO_OUTPUT: ${{ runner.temp }}/apt-repo
        run: .github/scripts/make-apt-repo.sh ./build-output "$APT_REPO_OUTPUT"

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        env:
          APT_REPO_OUTPUT: ${{ runner.temp }}/apt-repo
        with:
          path: ${{ env.APT_REPO_OUTPUT }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
